export const PERFORM_CARD_VERIFICATION = "PERFORM_CARD_VERIFICATION"
export const ERROR_ON_PERFORM_CARD_VERIFICATION = "ERROR_ON_PERFORM_CARD_VERIFICATION"
export const GENERATE_STATISTICS = "GENERATE_STATISTICS"
export const ERROR_ON_GENERATE_STATISTICS = "ERROR_ON_GENERATE_STATISTICS"
